version: '3.8'

services:
  easyrag:
    build: .
    container_name: easyrag_app
    ports:
      - "8028:8028"
    volumes:
      # 数据库文件映射到宿主机
      - ${DATA_PATH:-./data}/easyrag/db:/app/db
      # 日志文件映射到宿主机
      - ${DATA_PATH:-./data}/easyrag/logs:/app/logs
      # 模型文件映射到宿主机
      - ${DATA_PATH:-./data}/easyrag/models:/app/models_file
      # 上传文件映射到宿主机
      - ${DATA_PATH:-./data}/easyrag/files:/app/files
      # 临时文件映射到宿主机
      - ${DATA_PATH:-./data}/easyrag/temp:/app/temp_files
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8028
      - API_BASE_URL=http://localhost:8028
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8028/kb/list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - easyrag_network

networks:
  easyrag_network:
    driver: bridge 